# fly.toml app configuration file for fastapi-boilerplate-backend-prod
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'fastapi-boilerplate-backend-prod'
primary_region = 'iad'

[build]
  dockerfile = "docker/Dockerfile.prod"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop' # on, off, stop - stop is the default and will stop the machines after 10 minutes of inactivity. In production change it to 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[http_service.concurrency]
  type = "connections"
  hard_limit = 100
  soft_limit = 80

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/v1/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2

[deploy]
  strategy = "rolling"
