"""Add billing cycle support

Revision ID: 274eb79b752a
Revises: 81d1a2048a01
Create Date: 2025-01-24 11:35:46.392403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274eb79b752a'
down_revision: Union[str, None] = '81d1a2048a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('max_projects', sa.Integer(), nullable=False))
    op.add_column('teams', sa.Column('active_projects', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'active_projects')
    op.drop_column('teams', 'max_projects')
    # ### end Alembic commands ###
