"""Make team/project optional in activity logs

Revision ID: 68ccdf362ad1
Revises: 8dc2a3b98482
Create Date: 2025-01-24 11:03:08.440862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ccdf362ad1'
down_revision: Union[str, None] = '8dc2a3b98482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
