"""rename metadata column and add activity log fields

Revision ID: 8dc2a3b98482
Revises: 3c00a136a39e
Create Date: 2025-01-24 10:54:41.236800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dc2a3b98482'
down_revision: Union[str, None] = '3c00a136a39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats')
    op.add_column('activity_logs', sa.Column('action_type', sa.String(length=20), nullable=False))
    op.add_column('activity_logs', sa.Column('metadata', sa.JSON(), nullable=True))
    op.add_column('activity_logs', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('activity_logs', sa.Column('user_agent', sa.Text(), nullable=True))
    op.alter_column('activity_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index('ix_activity_logs_action_type', 'activity_logs', ['action_type'], unique=False)
    op.create_index('ix_activity_logs_created_at', 'activity_logs', ['created_at'], unique=False)
    op.create_index('ix_activity_logs_team_user', 'activity_logs', ['team_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_logs_team_user', table_name='activity_logs')
    op.drop_index('ix_activity_logs_created_at', table_name='activity_logs')
    op.drop_index('ix_activity_logs_action_type', table_name='activity_logs')
    op.alter_column('activity_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('activity_logs', 'user_agent')
    op.drop_column('activity_logs', 'ip_address')
    op.drop_column('activity_logs', 'metadata')
    op.drop_column('activity_logs', 'action_type')
    op.create_table('chats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sender_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='chats_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chats_pkey')
    )
    # ### end Alembic commands ###
