"""Seed data for subscription plans."""
from src.subscriptions.models import SubscriptionPlan

def create_subscription_plans():
    """Create subscription plan seed data."""
    plans = [
        SubscriptionPlan(
            name='free',
            display_name='Free',
            description='Perfect for trying out the platform',
            stripe_price_id_monthly=None,
            stripe_price_id_yearly=None,
            stripe_product_id=None,
            price_monthly_usd=0,
            price_yearly_usd=0,
            price_monthly_eur=0,
            price_yearly_eur=0,
            price_monthly_gbp=0,
            price_yearly_gbp=0,
            price_monthly_brl=0,
            price_yearly_brl=0,
            max_projects=1,
            max_users=1,
            max_storage_gb=1,
            features={'features': ['1 project', '1 user', '1GB storage', 'Basic support']},
            is_active=True,
            sort_order=1,
        ),
        SubscriptionPlan(
            name='starter',
            display_name='Starter',
            description='Perfect for getting started',
            stripe_price_id_monthly='price_starter_monthly',
            stripe_price_id_yearly='price_starter_yearly',
            stripe_product_id='prod_starter',
            price_monthly_usd=990,
            price_yearly_usd=9900,
            price_monthly_eur=890,
            price_yearly_eur=8900,
            price_monthly_gbp=790,
            price_yearly_gbp=7900,
            price_monthly_brl=4990,
            price_yearly_brl=49900,
            max_projects=3,
            max_users=5,
            max_storage_gb=5,
            features={'features': ['3 projects', '5 team members', '5GB storage', 'Basic support']},
            is_active=True,
            sort_order=2,
        ),
        SubscriptionPlan(
            name='pro',
            display_name='Professional',
            description='For growing teams',
            stripe_price_id_monthly='price_pro_monthly',
            stripe_price_id_yearly='price_pro_yearly',
            stripe_product_id='prod_pro',
            price_monthly_usd=2990,
            price_yearly_usd=29900,
            price_monthly_eur=2690,
            price_yearly_eur=26900,
            price_monthly_gbp=2390,
            price_yearly_gbp=23900,
            price_monthly_brl=14990,
            price_yearly_brl=149900,
            max_projects=10,
            max_users=20,
            max_storage_gb=50,
            features={'features': ['10 projects', '20 team members', '50GB storage', 'Priority support', 'Advanced analytics']},
            is_active=True,
            sort_order=3,
        ),
        SubscriptionPlan(
            name='business',
            display_name='Business',
            description='For large organizations',
            stripe_price_id_monthly='price_business_monthly',
            stripe_price_id_yearly='price_business_yearly',
            stripe_product_id='prod_business',
            price_monthly_usd=9990,
            price_yearly_usd=99900,
            price_monthly_eur=8990,
            price_yearly_eur=89900,
            price_monthly_gbp=7990,
            price_yearly_gbp=79900,
            price_monthly_brl=49990,
            price_yearly_brl=499900,
            max_projects=50,
            max_users=100,
            max_storage_gb=500,
            features={'features': ['Unlimited projects', '100 team members', '500GB storage', '24/7 priority support', 'Advanced analytics', 'Custom integrations', 'Dedicated account manager']},
            is_active=True,
            sort_order=4,
        ),
    ]
    return plans
