"""Seed data for subscription plans."""
from src.subscriptions.models import SubscriptionPlan

def create_subscription_plans():
    """Create subscription plan seed data."""
    plans = [
        SubscriptionPlan(
            name='free',
            display_name='Free',
            description='Perfect for trying out the platform',
            stripe_price_id_monthly=None,
            stripe_price_id_yearly=None,
            stripe_product_id=None,
            price_monthly_usd=0,
            price_yearly_usd=0,
            price_monthly_eur=0,
            price_yearly_eur=0,
            price_monthly_gbp=0,
            price_yearly_gbp=0,
            price_monthly_brl=0,
            price_yearly_brl=0,
            max_projects=1,
            max_users=1,
            max_storage_gb=1,
            max_ai_credits_monthly=10,
            ai_features_enabled=['documents'],
            features={'features': ['1 project', '1 user', '1GB storage', 'Basic support']},
            is_active=True,
            sort_order=1,
        ),
        SubscriptionPlan(
            name='starter',
            display_name='Starter Plan',
            description='Entry-level plan for small businesses',
            stripe_price_id_monthly='price_1Rsk6eD9jtDTgtt7wOVii0Uv',
            stripe_price_id_yearly='price_1Rsk6fD9jtDTgtt7atHuhVi0',
            stripe_product_id='prod_SmwOSjZOdHh8R2',
            price_monthly_usd=2800,
            price_yearly_usd=19900,
            price_monthly_eur=2520,
            price_yearly_eur=17910,
            price_monthly_gbp=2240,
            price_yearly_gbp=15920,
            price_monthly_brl=14000,
            price_yearly_brl=99500,
            max_projects=3,
            max_users=5,
            max_storage_gb=5,
            max_ai_credits_monthly=1000,
            ai_features_enabled=['documents', 'content'],
            features={'features': ['3 projects', '5 team members', '5GB storage', 'Basic support']},
            is_active=True,
            sort_order=2,
        ),
        SubscriptionPlan(
            name='pro',
            display_name='Pro Plan',
            description='Monthly premium subscription with advanced features',
            stripe_price_id_monthly='price_1Rsk6gD9jtDTgtt7D6J4QE4k',
            stripe_price_id_yearly='price_1Rsk6gD9jtDTgtt7KbZqwLhV',
            stripe_product_id='prod_SmwOCZUzUTQ5Zi',
            price_monthly_usd=6800,
            price_yearly_usd=45000,
            price_monthly_eur=6120,
            price_yearly_eur=40500,
            price_monthly_gbp=5440,
            price_yearly_gbp=36000,
            price_monthly_brl=34000,
            price_yearly_brl=225000,
            max_projects=10,
            max_users=20,
            max_storage_gb=50,
            max_ai_credits_monthly=5000,
            ai_features_enabled=['documents', 'content', 'analytics'],
            features={'features': ['10 projects', '20 team members', '50GB storage', 'Priority support', 'Advanced analytics']},
            is_active=True,
            sort_order=3,
        ),
        SubscriptionPlan(
            name='business',
            display_name='Business Plan',
            description='Full-featured enterprise package with custom support',
            stripe_price_id_monthly='price_1Rsk6bD9jtDTgtt7YVFraetI',
            stripe_price_id_yearly='price_1Rsk6dD9jtDTgtt7qEkMYgBF',
            stripe_product_id='prod_SmwOdGQRNlyp3D',
            price_monthly_usd=25500,
            price_yearly_usd=199900,
            price_monthly_eur=22950,
            price_yearly_eur=179910,
            price_monthly_gbp=20400,
            price_yearly_gbp=159920,
            price_monthly_brl=127500,
            price_yearly_brl=999500,
            max_projects=50,
            max_users=100,
            max_storage_gb=500,
            max_ai_credits_monthly=25000,
            ai_features_enabled=['documents', 'content', 'analytics'],
            features={'features': ['Unlimited projects', '100 team members', '500GB storage', '24/7 priority support', 'Advanced analytics', 'Custom integrations', 'Dedicated account manager']},
            is_active=True,
            sort_order=4,
        ),
    ]
    return plans
